# Generated by Django 5.1 on 2024-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="add_date",
            field=models.DateField(verbose_name="Дата поступления на склад"),
        ),
        migrations.AlterField(
            model_name="record",
            name="storage_date",
            field=models.DateField(verbose_name="Дата хранения до"),
        ),
    ]
