# Generated by Django 5.1 on 2024-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_record_add_date_alter_record_storage_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Введите комментарий",
                max_length=150,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="recipient",
            field=models.TextField(
                help_text="Введите имя заказчика",
                max_length=150,
                verbose_name="Заказчик",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="text",
            field=models.TextField(
                help_text="Введите наименование",
                max_length=150,
                verbose_name="Наименование",
            ),
        ),
    ]
