# Generated by Django 5.1 on 2024-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_record_comment_alter_record_recipient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="text",
            new_name="name",
        ),
    ]
