# Generated by Django 5.1 on 2024-08-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_rename_text_record_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="name",
            field=models.TextField(
                help_text="Введите наименование",
                max_length=15,
                verbose_name="Наименование",
            ),
        ),
    ]
