# Generated by Django 5.1 on 2024-08-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_record_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={
                "ordering": ["add_date"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AddField(
            model_name="record",
            name="marking",
            field=models.CharField(
                default=1,
                help_text="Введите маркировку",
                max_length=30,
                verbose_name="Маркировка",
            ),
            preserve_default=False,
        ),
    ]
