# Generated by Django 5.1 on 2024-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_alter_record_options_record_marking"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="amount",
            field=models.IntegerField(
                default=1,
                help_text="Введите количество мест",
                verbose_name="Количество мест",
            ),
            preserve_default=False,
        ),
    ]
