# Generated by Django 5.1 on 2024-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_record_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="volume",
            field=models.IntegerField(
                default=1, help_text="Введите объем в м³", verbose_name="Объем"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="weight",
            field=models.IntegerField(
                default=2, help_text="Введите вес в килограммах", verbose_name="Вес"
            ),
            preserve_default=False,
        ),
    ]
