# Generated by Django 5.1 on 2024-08-19 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_alter_record_volume_alter_record_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={
                "ordering": ["-add_date"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.RemoveField(
            model_name="record",
            name="storage_date",
        ),
    ]
