# Generated by Django 5.1 on 2024-08-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_alter_record_options_remove_record_storage_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="issue_date",
            field=models.DateField(
                blank=True, default=None, verbose_name="Дата выдачи"
            ),
            preserve_default=False,
        ),
    ]
