# Generated by Django 5.1 on 2024-08-19 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_alter_record_issue_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="issue_date",
        ),
    ]
