# Generated by Django 5.1 on 2024-08-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_remove_record_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
        ),
    ]
